version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: BuilderTools
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
     - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: